matrix:
  include:

  - language: python
    services:
      - postgresql
    before_script:
      - cd backend/
      - pip install -r requirements.txt
    script:
      - coverage run --source=database manage.py test
    after_success:
      coveralls
      
  - language: node_js
    node_js:
      - "node"
    install:
      - cd client/
      - npm install
    script:
      - npm test