version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - migration
      - db
  migration:
    image: postgres
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
