# Generated by Django 2.2.3 on 2019-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('user_size', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='household_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default='Will'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='household_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='household_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_id',
            field=models.TextField(null=True),
        ),
    ]
